#%RAML 1.0
Email:
  type: string
  minLength: 1
  pattern: ^.+@.+\..+$

User:
  type: object
  properties:
    id: integer
    email: Email
    firstName:
      type: string
      minLength: 1
    lastName:
      type: string
      minLength: 1
    emailVerified: boolean
    disabled: boolean
    absent: boolean

EmailRegistration:
  type: object
  properties:
    email: Email
    firstName:
      type: string
      minLength: 1
    lastName:
      type: string
      minLength: 1
    password:
      type: string
      minLength: 1
    absent: boolean

InvitationRegistration:
  type: object
  properties:
    firstName:
      type: string
      minLength: 1
    lastName:
      type: string
      minLength: 1
    password:
      type: string
      minLength: 1
    invitationCode:
      type: string
      minLength: 16
      maxLength: 16
    absent: boolean

LoginCredentials:
  type: object
  properties:
    email: Email
    password:
      type: string
      minLength: 1

TokenResponse:
  type: object
  properties:
    token:
      type: string
      pattern: ^[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$
      description: JWT token
    tokenId:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 20
      maxLength: 20
      description: JWT ID (jti)
    validFor:
      type: integer
      minimum: 1
      description: |
        Validity duration in seconds (excluding server-side grace period)

Error:
  type: object
  properties:
    error:
      type: object
      properties:
        code:
          type: string
          minLength: 1
        message: string

Turn:
  type: object
  properties:
    userId: integer
    startDate:
      type: datetime
      format: rfc3339

RequestTask:
  type: object
  properties:
    title:
      type: string
      minLength: 1
    description:
      type: string
      minLength: 1
    frequency:
      type: integer
      minimum: 1
      description: |
        Number of days between two executions of this task
    completionTime:
      type: integer
      minimum: 1
      description: |
        Time to be allowed for the task to be completed in hours
    users:
      type: integer[]
      minItems: 1
      description: |
        All users that will have to complete this task at one point or another

Task:
  type: object
  properties:
    id: integer
    title:
      type: string
      minLength: 1
    description:
      type: string
      minLength: 1
    frequency:
      type: integer
      minimum: 1
      description: |
        Number of days between two executions of this task
    completionTime:
      type: integer
      minimum: 1
      description: |
        Time to be allowed for the task to be completed in hours
    users:
      type: integer[]
      minItems: 1
      description: |
        All users that will have to complete this task at one point or another.
    currentTurn:
      type: Turn | nil
    upcomingTurns:
      type: Turn[]

Info:
  type: object
  properties:
    version:
      type: string
      example: "v0.1"
      pattern: ^v\d+(\.\d){1,2}$
      description: Version of the server
    currentTime:
      type: string
      example: "2018-02-12T15:41:42.799328781Z"
      description: Current time of the server
    name:
      type: string
      example: "core"
      description: Name of the implementation of the server

Invitation:
  type: object
  properties:
    id: integer
    email: Email
